config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users do
        resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"

	resources :patients  do 
 		resources :medical_records,
 		only: [:index, :show]
 	end 

 	resources :doctors do
 		get "/medical_records/patient_input", to: 'medical_records#patient_input', as: 'MR_patient_input'
 		post "/medical_records/patient_input", to: 'medical_records#patient_submit', as: 'MR_patient_submit'
 		get "/medical_records/input", to: 'medical_records#record_input', as: 'MR_input'
 		post "/medical_records/input", to: 'medical_records#record_submit', as: 'MR_submit'
 		get "/medical_records/medication_input", to: 'medications#medications_input', as: 'medications_input'
 		post "/medical_records/medication_input", to: 'medications#medications_submit', as: 'medications_submit'
        get '/medical_records/completed', to: 'medical_records#completed', as: 'MR_completed'
    get '/appointment/patient_input', to: 'appointments#patient_input', as: 'appointment_patient_input'
    post '/appointment/patient_input', to: 'appointments#patient_submit', as: 'appointment_patient_submit'
    get '/appointment/patient_medical_records', to: 'appointments#medical_record_index', as: 'appointment_patient_medical_records'

 	end 


 	resources :medical_records, only: [] do
    resources :appointments, only: [:index]
    get '/appointment/new', to: 'appointments#new', as: 'new_appointment'
    post '/appointment', to: 'appointments#create', as: 'appointment'
    get '/appointment/medication_input', to: 'appointments#medication_input', as: 'appointment_medications_input'
    post '/appointment/medication_submit', to: 'appointments#medication_submit', as: 'appointment_medications_submit'
    get '/appointment/completed', to: 'appointments#completed', as: 'appointment_completed'
 	end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one :doctor
  has_one :patient, inverse_of: :user
  accepts_nested_attributes_for :patient
  enum role: [:patient, :doctor]

  validates_presence_of :full_name, :identity_card, :contact_number, :street_address, :postcode, :city, :country
  validates_uniqueness_of :identity_card
  validates_format_of :identity_card, with: /\A\d{6}-\d{2}-\d{4}\z/
  validates_format_of :contact_number, with: /\d{6,}/

end

app/controllers/concerns/users_controller.rb
class UsersController < Clearance::UsersController
	def index
	end


 end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def index
    @user = current_user
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save!
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.js   {}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.js   {}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = current_user
  end 

    private

    def user_params
      params[:user].permit(:email, :password, :full_name, :identity_card, :street_address,:postcode, :city, :country, :contact_number)
    end
end

app/views/users/_errors.html.erb
<h2>
  <%= pluralize(@user.errors.count, "error") %> found.
</h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for @user, :html => {class: 'form-horizontal'} do |form| %>


<div class="form-group">
  <label for="inputFullName" class="control-label col-xs-2">
  <%= form.label :full_name %></label>
  <div class="col-xs-10"><%= form.text_field :full_name, type: 'full_name' %></div>
</div>

<div class="form-group">
  <label for="inputIdentityCard" class="control-label col-xs-2">
  <%= form.label :identity_card %></label>
  <div class="col-xs-10"><%= form.text_field :identity_card, type: 'identity_card' %></div>
</div>

<div class="form-group">
  <label for="inputEmail" class="control-label col-xs-2">
  <%= form.label :email %></label>
  <div class="col-xs-10"><%= form.text_field :email, type: 'email' %></div>
</div>

<div class="form-group">
  <label for="inputContactNumber" class="control-label col-xs-2">
  <%= form.label :contact_number %></label>
  <div class="col-xs-10"><%= form.text_field :contact_number %></div>
</div>

<div class="form-group">
<div class="password-field">
  <label for="inputPassword" class="control-label col-xs-2"><%= form.label :password %></label>
  <div class="col-xs-10"><%= form.password_field :password %></div>
</div></div>

<div class="form-group">
  <label for="inputStreetAddress" class="control-label col-xs-2"><%= form.label :street_address %></label>
  <div class="col-xs-10"><%= form.text_field :street_address %></div>
</div>

<div class="form-group">
  <label for="inputPostcode" class="control-label col-xs-2">
  <%= form.label :postcode %></label>
  <div class="col-xs-10"><%= form.text_field :postcode %></div>
</div>

<div class="form-group">
  <label for="inputCity" class="control-label col-xs-2">
  <%= form.label :city %></label>
  <div class="col-xs-10"><%= form.text_field :city %></div>
</div>

<div class="form-group">
  <label for="inputCountry" class="control-label col-xs-2">
  <%= form.label :country %></label>
  <div class="col-xs-10"><%= form.text_field :country %></div>
</div>

<div class="form-group">
<div class="submit-field">
<label for="inputCountry" class="control-label col-xs-2">
    <%= form.submit %>
</div></div>
<% end %>

app/views/users/create.js.erb
$('#new_user').html("<%= j render 'errors', locals: @user %>");

app/views/users/edit.html.erb
<!-- Page Content -->
<div class="container">
	<div class="col-md-8 col-md-offset-2">
	<br>
		<p class="lead"><strong> Recent Appointments </strong></p>
		<div class="list-group">
			<a href="#" class="list-group-item">Appointment - 	05/01/2017</a>
			<a href="#" class="list-group-item">Appointment - 	30/12/2016</a>
			<a href="#" class="list-group-item">Check Up - 		20/12/2016 </a>
			<a href="#" class="list-group-item">Appointment - 	05/11/2016</a>
			<a href="#" class="list-group-item">Appointment - 	30/11/2016</a>
			<a href="#" class="list-group-item">Check Up - 		20/10/2016 </a>
			<a href="#" class="list-group-item">Appointment - 	05/09/2016</a>
			<a href="#" class="list-group-item">Appointment - 	30/09/2016</a>
			<a href="#" class="list-group-item">Check Up - 		20/08/2016 </a>
			<a href="#" class="list-group-item">Appointment - 05/06/2015</a>
			<a href="#" class="list-group-item">Appointment - 30/06/2015</a>
			<a href="#" class="list-group-item">Check Up - 20/05/2015 </a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
<h1><%= @user.full_name + "'s" + " Index"%></h1>
  <div class="row">

  		<div class="col-md-8">
      
  		<p class="lead">Upcoming Appointments</p>
      <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
       
      </div>
    </div>


    <div class="col-md-4">
    <p class="lead">Quick Link</p>
      <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
       
      </div>
    </div>

  </div> <!-- row -->
</div> <!-- container -->

<div class="container">
  <div class="row">
    <div class="col-md-8">

    <p class="lead">Notifications</p>
      <div class="list-group">
        <a href="#" class="list-group-item">Medication</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
       
      </div>
    </div><!-- col-md-8 -->
  </div><!-- row -->
</div><!-- container -->

app/views/users/new-backup.html.erb
<div id="clearance" class="sign-up">
    <h2>
    <%= t(".title") %>
    </h2>
    <%= @error_msg %>

    <%= render partial: '/users/form' %>
</div>

app/views/users/new.html.erb
<center>
	<div class="container">
		<div class="jumbotron">
			<h1>Med Base</h1>
			<p>Managing Your Health</p>
	</div>
	<h3>
		<p>
			<span class="glyphicon glyphicon-user"></span><br>
			<a href="<%= new_patient_path %>">Sign up - Patients</a>
		</p>
	</h3>
	<br>

	<h3>
		<p>
			<i class="fa fa-ambulance" aria-hidden="true"></i>
			<br>
			<a href="<%= new_doctor_path %>">Sign up - Doctors</a>
		</p>
	</h3>
</div>


</center>

app/views/users/show.html.erb
<!-- Page Content -->
<div class="container">
<h1><%= "Welcome, "+  @user.full_name %></h1>
	<div class="row">
		<div class="col-md-4">
			
			<p class="lead">Basic Info</p>
			<div class="list-group">
			<div class="list-group-item">Age: 30</a></div>
				<div class="list-group-item">Email:
				<%= @user.email %></div>
				<div class="list-group-item">Gender: Male</a></div>
				<div class="list-group-item">Height: 175 CM</a></div>
				<div class="list-group-item">Weight: 75 kg</a></div>
				<div class="list-group-item">BloodType: O+ </a></div>
				<div class="list-group-item"><%= button_to "Edit Profile", edit_user_path(current_user), method: :get %></div>
				
			</div>
		</div>
		<div class="col-md-8 pull-right">
			<p class="lead">Medical Records History [Date of Recent Appointment]</p>
			<div class="list-group">
				<a href="#" class="list-group-item">Appointment - 05/01/2017</a>
				<a href="#" class="list-group-item">Appointment - 30/12/2016</a>
				<a href="#" class="list-group-item">Check Up - 20/12/2016 </a>
				
			</div>
		</div>
		<div class="col-md-8 pull-right">
			<p class="lead">Current Allergies</p>
			<div class="list-group">
				<div class="list-group-item">Medication - Penicillin</a></div>
				<div class="list-group-item">Food - Anaphylaxis</a></div>
				<div class="list-group-item">Skin</a></div>
				
			</div>
		</div>
		<div class="col-md-8 pull-right">
			<p class="lead">Current Medications & Supplements</p>
			<div class="list-group">
				<div class="list-group-item">Prozac</a></div>
				<div class="list-group-item">Panadol</a></div>

			</div>
		</div>
		</div> 
		</div> 