config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users do
        resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"

	resources :patients  do 
 		resources :medical_records,
 		only: [:index, :show]
 	end 

 	resources :doctors do
 		get "/medical_records/patient_input", to: 'medical_records#patient_input', as: 'MR_patient_input'
 		post "/medical_records/patient_input", to: 'medical_records#patient_submit', as: 'MR_patient_submit'
 		get "/medical_records/input", to: 'medical_records#record_input', as: 'MR_input'
 		post "/medical_records/input", to: 'medical_records#record_submit', as: 'MR_submit'
 		get "/medical_records/medication_input", to: 'medications#medications_input', as: 'medications_input'
 		post "/medical_records/medication_input", to: 'medications#medications_submit', as: 'medications_submit'
        get '/medical_records/completed', to: 'medical_records#completed', as: 'MR_completed'
    get '/appointment/patient_input', to: 'appointments#patient_input', as: 'appointment_patient_input'
    post '/appointment/patient_input', to: 'appointments#patient_submit', as: 'appointment_patient_submit'
    get '/appointment/patient_medical_records', to: 'appointments#medical_record_index', as: 'appointment_patient_medical_records'

 	end 


 	resources :medical_records, only: [] do
    resources :appointments, only: [:index]
    get '/appointment/new', to: 'appointments#new', as: 'new_appointment'
    post '/appointment', to: 'appointments#create', as: 'appointment'
    get '/appointment/medication_input', to: 'appointments#medication_input', as: 'appointment_medications_input'
    post '/appointment/medication_submit', to: 'appointments#medication_submit', as: 'appointment_medications_submit'
    get '/appointment/completed', to: 'appointments#completed', as: 'appointment_completed'
 	end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  has_many :medical_records
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController


	def new
		@user = User.new
		@medical_categories = MedicalCategory.all
	end

	def create
		@user = User.new(user_params)
		if @user.save
			@user.doctor!
			@doctor = Doctor.new(user_id: @user.id, specialization: params[:specialization])
			@doctor.save
			sign_in(@user)
			flash[:success] = "Doctor account successfully created!"
			redirect_to doctor_path(@doctor)
		else
			flash[:danger] = 'Input Error'
			redirect_to new_doctor_path
		end
	end

	def show
		@user = current_user
		@doctor = @user.doctor
	end 

	private

	def user_params
    params[:user].permit(:email, :password, :full_name, :identity_card, :street_address,:postcode, :city, :country, :contact_number)
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/new.html.erb
<div class="container">

  <%= form_for @user, url: doctors_path, :html => {class: 'form-horizontal'} do |form| %>

  <div class="form-group">
    <div class="control-label col-md-4">
      Full Name:
      </div>
        <div class="col-md-4">
            <%= form.text_field :full_name, type: 'full_name', class: 'form-control' %>
        </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-4">
      Identity Card: 
    </div>
    <div class="col-md-4">
      <%= form.text_field :identity_card, type: 'identity_card', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-4">
      Email: 
    </div>
    <div class="col-md-4">
      <%= form.text_field :email, type: 'email', class: 'form-control' %>
    </div> 
  </div>


  <div class="form-group">
    <div class="control-label col-md-4">
      Contact Number: 
    </div>
    <div class="col-md-4">
      <%= form.text_field :contact_number, class: 'form-control' %>
    </div> 
  </div>


  <div class="form-group">
    <div class="control-label col-md-4">
      <div class="password-field">
        Password: 
      </div>
    </div>
    <div class="col-md-4">
    <%= form.password_field :password, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <div class="control-label col-md-4">
      Street Address: 
    </div>
    <div class="col-md-4">
      <%= form.text_field :street_address, class: 'form-control' %>
    </div>
  </div>
   
  <div class="form-group">  
    <div class="control-label col-md-4">
      Postcode: 
    </div>
    <div class="col-md-4">
    <%= form.text_field :postcode, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-4">
      City: 
    </div>
    <div class="col-md-4">
      <%= form.text_field :city, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-4">
      Country:
    </div>
    <div class="col-md-4">
      <%= form.text_field :country, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-4">
      Specialization: 
    </div>
    <div class="col-md-4">
      <select class="form-control" id="specialization-select" name="specialization">
          <option> Neurology</option>
          <option>Orthopaedics</option>
          <option>Cancer</option>
          <option>Paediatrics</option>
          <option>Ear</option> Nose and Throat</option>
          <option>Ophthalmology</option>
          <option>Cardiovascular</option>
          <option>Endocrinology</option>
          <option>Renal Disorders</option>
          <option>Respiratory Disorders</option>
          <option>Gastroenterology</option>
          <option>Urinary & Reproductive System</option>
          <option>Obstetrics & Gynaecology</option>
          <option>Oral and Maxillofacial</option>
          <option>Dermatology</option>
          <option>Geriatic Disorders</option>
          <option>Haematology</option>
          <option>Psychiatry</option>
          <option>Infectious Diseases</option>
          <option>Rheumatology</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <div class="control-label col-md-6">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>


  <% end %>
</div>

app/views/doctors/show.html.erb
<!-- Page Content -->
<div class="container">
	<h1><%= "Welcome, DR "+  @user.full_name %></h1>
	
	<div class="row">
		<div class="col-md-4">
			<p class="lead">Basic Info</p>
			<div class="list-group">
				<div class="list-group-item">
					<%= "Specialization: " + @doctor.specialization.to_s %></a>
				</div>
				<div class="list-group-item">
					<%= "Email: " + @user.email %>
				</div>
				<div class="list-group-item">
					<%= button_to "Edit Profile", edit_user_path(current_user), method: :get %>
				</div>
			</div>
		</div>
	
		<div class="col-md-8 pull-right">
			<p class="lead">
			Medical Records History [Date of Recent Appointment]
			</p>
				<div class="list-group">
					<div class="list-group-item">Appointment - 05/01/2017</a>
					</div>
					<div class="list-group-item">Appointment - 30/12/2016</a>
					</div>
					<div class="list-group-item">Check Up - 20/12/2016 </a>
					</div>
				</div>
		</div>	
	</div> 
</div> 