config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users do
        resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"

	resources :patients  do 
 		resources :medical_records,
 		only: [:index, :show]
 	end 

 	resources :doctors do
 		get "/medical_records/patient_input", to: 'medical_records#patient_input', as: 'MR_patient_input'
 		post "/medical_records/patient_input", to: 'medical_records#patient_submit', as: 'MR_patient_submit'
 		get "/medical_records/input", to: 'medical_records#record_input', as: 'MR_input'
 		post "/medical_records/input", to: 'medical_records#record_submit', as: 'MR_submit'
 		get "/medical_records/medication_input", to: 'medications#medications_input', as: 'medications_input'
 		post "/medical_records/medication_input", to: 'medications#medications_submit', as: 'medications_submit'
        get '/medical_records/completed', to: 'medical_records#completed', as: 'MR_completed'
    get '/appointment/patient_input', to: 'appointments#patient_input', as: 'appointment_patient_input'
    post '/appointment/patient_input', to: 'appointments#patient_submit', as: 'appointment_patient_submit'
    get '/appointment/patient_medical_records', to: 'appointments#medical_record_index', as: 'appointment_patient_medical_records'

 	end 


 	resources :medical_records, only: [] do
    resources :appointments, only: [:index]
    get '/appointment/new', to: 'appointments#new', as: 'new_appointment'
    post '/appointment', to: 'appointments#create', as: 'appointment'
    get '/appointment/medication_input', to: 'appointments#medication_input', as: 'appointment_medications_input'
    post '/appointment/medication_submit', to: 'appointments#medication_submit', as: 'appointment_medications_submit'
    get '/appointment/completed', to: 'appointments#completed', as: 'appointment_completed'
 	end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :medical_record
  has_many :medications
  validates_presence_of :appointment_date, :notes
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	def index
		@appointments = Appointment.where(medical_record_id: params[:medical_record_id]).order(created_at: :desc)
	end

	def patient_input
		render '/appointments/patient_input'
	end

	def patient_submit
		@user = User.find_by(identity_card: params[:identity_card])
		if @user && @user.patient?
			session[:patient_id] = @user.patient.id
			redirect_to doctor_appointment_patient_medical_records_path(current_user.doctor)
		else
			flash[:danger] = 'Patient not found'
			redirect_to doctor_appointment_patient_input_path(current_user.doctor)
		end
	end

	def medical_record_index
		@patient = Patient.find(session[:patient_id])
		@medical_records = MedicalRecord.where(doctor_id: current_user.doctor.id, patient_id: session[:patient_id])
		render '/appointments/patient_medical_records'
	end

	def new
		@patient = Patient.find(session[:patient_id])
		@medical_record = MedicalRecord.find(params[:medical_record_id])
		@appointment = Appointment.new
	end

	def create
		session[:appoinment_id] = nil
		@appointment = MedicalRecord.find(params[:medical_record_id]).appointments.new(appointment_params)
		if @appointment.save
			session[:appointment_id] = @appointment.id
			flash[:success] = 'Appointment record created'
			redirect_to medical_record_appointment_medications_input_path(params[:medical_record_id])
		else
			flash[:danger] = 'Appointment creation failed'
			redirect_to medical_record_new_appointment_path(params[:medical_record_id])
		end
	end

	def medication_input
		@patient = Patient.find(session[:patient_id])
		@appointment = Appointment.find(session[:appointment_id])
		@medication = Medication.new
		render '/appointments/medication_input'
	end

	def medication_submit
		@medication = Appointment.find(session[:appointment_id]).medications.new(medication_params)
		if @medication.save
			redirect_to medical_record_appointment_medications_input_path(params[:medical_record_id])
		else
			flash[:danger] = 'Medication record creation failed'
			redirect_to medical_record_appointment_medications_input_path(params[:medical_record_id])
		end
	end

	def completed
		session[:patient_id] = nil
		session[:appointment_id] = nil
		redirect_to doctor_path(current_user.doctor)
	end

	private

	def appointment_params
		params[:appointment].permit(:appointment_date, :notes)
	end

	def medication_params
		params[:medication].permit(:name, :dosage)
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<h3 class="text-center">Your Appointment Records for <%= MedicalRecord.find(params[:medical_record_id]).medical_condition.name %></h3>
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <% @appointments.each do |appointment| %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Appointment #<%= appointment.id %> with <%= appointment.medical_record.doctor.user.full_name %></h3>
        </div>
        <div class="panel-body">
          <p>
            <strong>
              Appointment Date:<br>
            </strong>
            <%= appointment.appointment_date.strftime('%d %b %Y') %>
          </p>
          <p>
            <strong>
              Doctor's notes:<br>
            </strong>
            <%= appointment.notes %>
          </p>
          <br>
          <% if appointment.medications.any? %>
            <p>
              <strong>
                Prescription:
              </strong>
            </p>
            <table class="table">
              <thead>
                <tr>
                  <th class="col-md-3 med-record-index-table-header">
                    Medication
                  </th>
                  <th class="col-md-2 med-record-index-table-header">
                    Dosage
                  </th>
                </tr>
              </thead>
              <tbody>
                <% appointment.medications.each do |medication| %>
                  <tr>
                    <td>
                      <%= medication.name %>
                    </td>
                    <td>
                      <%= medication.dosage %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/medication_input.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
			<div class="panel-heading">
				<b>Records Summary for <%= @patient.user.full_name %></b>
			</div>
			<div class="panel-body">
				<p>
					<b>Medical Condition:</b><br>
					<%= MedicalRecord.find(params[:medical_record_id]).medical_condition.name %>
				</p>
				<p>
					<b>Appointment Date:</b><br>
					<%= @appointment.appointment_date.strftime('%d %b %Y') %>
				</p>
				<p>
					<b>Notes:</b><br>
					<%= @appointment.notes %>
				</p>

				<% if !Medication.find_by(appointment_id: session[:appointment_id]).nil? %>
					<br>
					<p><b>Prescription:</b></p>
          <table class="table">
            <thead>
              <tr>
                <th class="col-md-3 med-record-index-table-header">
                  Medication
                </th>
                <th class="col-md-2 med-record-index-table-header">
                  Dosage
                </th>
              </tr>
            </thead>
            <tbody>				
							<% Medication.where(appointment_id: session[:appointment_id]).each do |med| %>
								<tr>
	                <td>
	                  <%= med.name %>
	                </td>
	                <td>
	                  <%= med.dosage %>
	                </td>
	              </tr>
							<% end %>
						</tbody>
					</table>
				<% end %>
			</div>
		</div>

		<%= form_for @medication, url: medical_record_appointment_medications_submit_path(params[:medical_record_id]) do |form| %>
		 	<div class="form-group">
				<%= form.label 'Medication Name' %>
			 	<%= form.text_field :name, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= form.label 'Dosage' %>
				<%= form.text_field :dosage, class:"form-control" %>
			</div>
			<div class="form-group text-center">
				<%= form.submit 'Add Prescription', class:"btn btn-primary" %>
				<%= link_to 'Record Completed', medical_record_appointment_completed_path(params[:medical_record_id]), method: :get, class: 'btn btn-success' %>
			</div>
		<%end%>
	</div>
</div>

app/views/appointments/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
  <div class="panel panel-info">
  <div class="panel-heading">Patient Info</div>
      <div class="panel-body">
        <p><b>Full name:</b> <br><%= @patient.user.full_name %> <br>
        <p><b>IC:</b> <br><%= @patient.user.identity_card %></p>

        <p><b>Date of Birth:</b> <br><%= @patient.date_of_birth.strftime('%d %b %Y') %></p>
        <p><b>Medical Condition</b> <br><%= @medical_record.medical_condition.name %></p>
        </div>
      </div>

<%= form_for @appointment, url: medical_record_appointment_path(params[:medical_record_id]) do |form| %>


  <div class="form-group">
    <%= form.label :appointment_date %>
    <%= form.date_field :appointment_date, value: Date.today.strftime('%Y-%m-%d'), class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= submit_tag 'Submit and prescribe medication', class: 'btn btn-primary col-md-offset-3' %>
  </div>


<% end %>

</div>
</div>
</div>
</div>

app/views/appointments/patient_input.html.erb
<%= form_tag doctor_appointment_patient_submit_path(current_user.doctor), method: :post, class:"form-horizontal col-md-10 col-md-offset-2" do %>
	
	<div class="form-group">
		<%= label_tag "identity_card", "Patient IC number", class: "col-md-2 control-label" %>
		<div class="col-md-6">
			<%= text_field_tag :identity_card, nil, class: "form-control", placeholder: 'IC Number with dashes e.g. 880101-33-2353'%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-8 col-md-offset-2">
			<%= submit_tag'Submit', class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/appointments/patient_medical_records.html.erb
<!-- Page Content -->
<div class="container">
<h3>Medical Record for: <%= @patient.user.full_name %></h3>

	<div class="col-md-12">
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="col-md-2">
						Medical Record #
					</th>
					<th class="col-md-2">
						Medical Condition
					</th>
					<th class="col-md-2">
						Medical Category
					</th>
				</tr>
			</thead>
			<tbody>
				<% @medical_records.each do |rec| %>
					<tr>
						<td>
							<%= rec.id %>
						</td>
						<td>
							<a href="<%= medical_record_new_appointment_path(rec) %>"> <%= rec.medical_condition.name %> </a>
						</td>
						<td>
							<%= rec.medical_category.name %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>