config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users do
        resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"

	resources :patients  do 
 		resources :medical_records,
 		only: [:index, :show]
 	end 

 	resources :doctors do
 		get "/medical_records/patient_input", to: 'medical_records#patient_input', as: 'MR_patient_input'
 		post "/medical_records/patient_input", to: 'medical_records#patient_submit', as: 'MR_patient_submit'
 		get "/medical_records/input", to: 'medical_records#record_input', as: 'MR_input'
 		post "/medical_records/input", to: 'medical_records#record_submit', as: 'MR_submit'
 		get "/medical_records/medication_input", to: 'medications#medications_input', as: 'medications_input'
 		post "/medical_records/medication_input", to: 'medications#medications_submit', as: 'medications_submit'
        get '/medical_records/completed', to: 'medical_records#completed', as: 'MR_completed'
    get '/appointment/patient_input', to: 'appointments#patient_input', as: 'appointment_patient_input'
    post '/appointment/patient_input', to: 'appointments#patient_submit', as: 'appointment_patient_submit'
    get '/appointment/patient_medical_records', to: 'appointments#medical_record_index', as: 'appointment_patient_medical_records'

 	end 


 	resources :medical_records, only: [] do
    resources :appointments, only: [:index]
    get '/appointment/new', to: 'appointments#new', as: 'new_appointment'
    post '/appointment', to: 'appointments#create', as: 'appointment'
    get '/appointment/medication_input', to: 'appointments#medication_input', as: 'appointment_medications_input'
    post '/appointment/medication_submit', to: 'appointments#medication_submit', as: 'appointment_medications_submit'
    get '/appointment/completed', to: 'appointments#completed', as: 'appointment_completed'
 	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :medical_record
  has_many :medications
  validates_presence_of :appointment_date, :notes
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  has_many :medical_records
end

app/models/medical_category.rb
class MedicalCategory < ApplicationRecord
	has_many :medical_records
end

app/models/medical_condition.rb
class MedicalCondition < ApplicationRecord
	has_many :medical_records
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :medical_condition
  belongs_to :medical_category
  has_many :appointments
end

app/models/medication.rb
class Medication < ApplicationRecord
	belongs_to :appointment
	validates_presence_of :name, :dosage
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :medical_records
  validates_presence_of :date_of_birth, :gender, :height, :weight, :blood_type
  validates_inclusion_of :gender, in: %w( Male Female )
  validates_inclusion_of :height, in: 20..250
  validates_inclusion_of :weight, in: 5..400
  validates_inclusion_of :blood_type, in: %w( O A B AB )
  validate :date_of_birth_in_past

  def date_of_birth_in_past
  	if self.date_of_birth > Date.today
  		errors.add(:DOB, 'Date of birth can\'t be in future')
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one :doctor
  has_one :patient, inverse_of: :user
  accepts_nested_attributes_for :patient
  enum role: [:patient, :doctor]

  validates_presence_of :full_name, :identity_card, :contact_number, :street_address, :postcode, :city, :country
  validates_uniqueness_of :identity_card
  validates_format_of :identity_card, with: /\A\d{6}-\d{2}-\d{4}\z/
  validates_format_of :contact_number, with: /\d{6,}/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
  add_flash_types :danger, :info, :warning, :success

  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController


	def new
		@user = User.new
		@medical_categories = MedicalCategory.all
	end

	def create
		@user = User.new(user_params)
		if @user.save
			@user.doctor!
			@doctor = Doctor.new(user_id: @user.id, specialization: params[:specialization])
			@doctor.save
			sign_in(@user)
			flash[:success] = "Doctor account successfully created!"
			redirect_to doctor_path(@doctor)
		else
			flash[:danger] = 'Input Error'
			redirect_to new_doctor_path
		end
	end

	def show
		@user = current_user
		@doctor = @user.doctor
	end 

	private

	def user_params
    params[:user].permit(:email, :password, :full_name, :identity_card, :street_address,:postcode, :city, :country, :contact_number)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def new
		@user = User.new
		@user.build_patient
	end

	def create
		@user = User.new(user_params)
		if @user.save
			@user.patient!
			sign_in(@user)
			flash[:success] = "Patient account successfully created!"
			redirect_to patient_path(@user.patient)
		else
			flash[:danger] = 'Input Error'
			redirect_to new_patient_path
		end
	end

	def show
		@user = current_user
		@patient = @user.patient
	end 

	private

	def user_params
    params[:user].permit(:email, :password, :full_name, :identity_card, :street_address, :postcode, :city, :country, :contact_number, patient_attributes: [:date_of_birth, :gender, :height, :weight, :blood_type])
 	end
end

app/controllers/sessions_controller.rb
class UsersController < Clearance::UsersController

	def show
		
	end 
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  	if  signed_in?
  		if current_user.patient?
  		redirect_to patient_path(current_user.patient)
  		else 
  		redirect_to doctor_path(current_user.doctor)
  		end
  	else
  		redirect_to sign_in_path
  	end 
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def index
    @user = current_user
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save!
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.js   {}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.js   {}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = current_user
  end 

    private

    def user_params
      params[:user].permit(:email, :password, :full_name, :identity_card, :street_address,:postcode, :city, :country, :contact_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_flash_msgs.html.erb
<% flash.each do |name, msg| -%>
<div class="alert alert-<%= name %>">
  <%= msg %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->


<script src="https://use.fontawesome.com/a416a0a082.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



 <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" style="vertical-align: middle; font-size: 15px;" href="/">
      <span class="glyphicon glyphicon-heart-empty heart">Medbase</a></span>

    </div>

 <!--    <p class="navbar-text navbar-right">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
      <%#= link_to 'Sign In', sign_in_path, method: :get %>
    </p> -->

    <!-- navbar sign up in out  -->

    
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
      <li><%= link_to 'About Us' %></li>
      <li><%= link_to 'Services' %></li>
      <li><%= link_to 'Specialist' %></li>
      <li><%= link_to 'Product' %></li>
      <li><%= link_to 'Articles' %></li>
      <li><%= link_to 'Sign Out', sign_out_path, method: :delete%></li>
      <% else %>
      <li><%= link_to 'About Us' %></li>
      <li><%= link_to 'Services' %></li>
      <li><%= link_to 'Specialist' %></li>
      <li><%= link_to 'Product' %></li>
      <li><%= link_to 'Articles' %></li>
      <li><%= link_to 'Sign In', sign_in_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- nav tabs for PATIENTS NAVBAR -->
<ul class="nav nav-tabs">
<% if signed_in? %>
<% if current_user.patient? %>

  <li><%= link_to 'My Profile', patient_path(current_user) %></li>
  <li><%= link_to 'Appointments', edit_user_path(current_user) %></li>
  <li><%= link_to 'Medical Records', patient_medical_records_path(current_user.patient) %></li>
</ul>

<% else %>
<!-- nav tabs for DOCTORS NAVBAR -->

<ul class="nav nav-tabs">
  <li><%= link_to 'My Profile', doctor_path(current_user) %></li>
  <li><%= link_to 'New Appointment Record', doctor_appointment_patient_input_path(current_user.doctor) %></li>
  <li><%= link_to 'New Medical Record', doctor_MR_patient_input_path(current_user.doctor)%></li>
  <% end -%>
  <% end -%>
</ul>

</head>

<body>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="alert alert-<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>

</body>

</html>